sources:
  bundler: true

allowed:
  - mit
  - apache-2.0

reviewed:
  bundler:
    # bsd-3 and mit
    - ffi
  
    # ruby license
    - json
    - httpclient
    - pathname-common_prefix

    # bsd-2 or ruby
    - racc
    - ruby2_keywords

    # dwtfyw
    - reverse_markdown
